import 0.15

diff --git a/gettext-tools/tests/lang-objc b/gettext-tools/tests/lang-objc
--- a/gettext-tools/tests/lang-objc
+++ b/gettext-tools/tests/lang-objc
@@ -19,7 +19,9 @@ int main ()
 }
 EOF
 ${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o hello hello.m 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: Objective C compiler not found"
+       rm -fr $tmpfiles; exit 77
+     }
 
 tmpfiles="$tmpfiles prog.m"
 cat <<\EOF > prog.m
@@ -37,10 +39,8 @@ int main (int argc, char *argv[])
 
   xsetenv ("LC_ALL", argv[1], 1);
   if (setlocale (LC_ALL, "") == NULL)
-    {
-      fprintf (stderr, "Couldn't set locale.\n");
-      exit (77);
-    }
+    /* Couldn't set locale.  */
+    exit (77);
 
   textdomain ("prog");
   bindtextdomain ("prog", ".");
@@ -62,7 +62,10 @@ EOF
 top_builddir=..
 
 tmpfiles="$tmpfiles prog.${OBJEXT} prog${EXEEXT}"
-${LIBTOOL} --quiet --mode=link ${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o prog prog.m -I.. -I$top_srcdir/lib ../lib/libgettextlib.la -I../intl ${LTLIBINTL} \
+# Put the -I flags before ${CFLAGS} ${CPPFLAGS}, to make sure that libintl.h
+# is found in the build directory, regardless of -I options present in
+# ${CFLAGS} or ${CPPFLAGS}.
+${LIBTOOL} --quiet --mode=link ${CC} -I.. -I$top_srcdir/lib ../lib/libgettextlib.la -I../intl ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -o prog prog.m ${LTLIBINTL} \
   || exit 1
 
 tmpfiles="$tmpfiles prog.pot"
@@ -159,6 +162,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
diff --git a/gettext-tools/tests/lang-php b/gettext-tools/tests/lang-php
--- a/gettext-tools/tests/lang-php
+++ b/gettext-tools/tests/lang-php
@@ -65,11 +65,18 @@ test -d fr/LC_MESSAGES || mkdir fr/LC_MESSAGES
 : ${MSGFMT=msgfmt}
 ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
-# Test for presence of php version 4.0 or newer.
-case `(php -v) 2>/dev/null` in
+# Test for presence of php version 4.0 or newer with gettext support.
+(php -v) >/dev/null 2>/dev/null
+test $? -le 1 \
+  || { echo "Skipping test: php not found"; rm -fr $tmpfiles; exit 77; }
+case `php -v | sed -n -e 1p | sed -e 's/^[^0-9]*//'` in
   [4-9].*) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: php version too old"; rm -fr $tmpfiles; exit 77;;
 esac
+{ php -m | grep '^gettext$' >/dev/null; } \
+  || { echo "Skipping test: php was built without gettext support"
+       rm -fr $tmpfiles; exit 77
+     }
 
 # Test which of the fr_FR locales are installed.
 : ${LOCALE_FR=fr_FR}
@@ -91,6 +98,11 @@ if test $LOCALE_FR_UTF8 != none; then
   esac
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+  if test -f /usr/bin/localedef; then
+    echo "Skipping test: no french locale is installed"
+  else
+    echo "Skipping test: no french locale is supported"
+  fi
   rm -fr $tmpfiles; exit 77
 fi
 
diff --git a/gettext-tools/tests/lang-python-1 b/gettext-tools/tests/lang-python-1
--- a/gettext-tools/tests/lang-python-1
+++ b/gettext-tools/tests/lang-python-1
@@ -4,7 +4,7 @@
 
 # Note: This test fails with Python 2.3, 2.4 when an UTF-8 locale is present.
 # It looks like a bug in Python's gettext.py. This here is a quick workaround:
-LOCALE_FR_UTF8=none
+UTF8_LOCALE_UNSUPPORTED=yes
 
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
@@ -70,10 +70,10 @@ ${MSGFMT} -o fr/LC_MESSAGES/prog.mo fr.po
 
 # Test for presence of python version 2.0 or newer.
 (python -V) >/dev/null 2>/dev/null \
-  || { rm -fr $tmpfiles; exit 77; }
+  || { echo "Skipping test: python not found"; rm -fr $tmpfiles; exit 77; }
 case `python -c 'import sys; print sys.hexversion >= 0x20000F0'` in
   1 | True) ;;
-  *) rm -fr $tmpfiles; exit 77;;
+  *) echo "Skipping test: python version too old"; rm -fr $tmpfiles; exit 77;;
 esac
 
 tmpfiles="$tmpfiles prog.ok prog.oku prog.out"
@@ -93,12 +93,28 @@ if test $LOCALE_FR != none; then
   LANGUAGE= LC_ALL=$LOCALE_FR python prog.py > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
-if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog.py > prog.out || exit 1
-  ${DIFF} prog.oku prog.out || exit 1
-fi
-if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
-  rm -fr $tmpfiles; exit 77
+if test -z "$UTF8_LOCALE_UNSUPPORTED"; then
+  if test $LOCALE_FR_UTF8 != none; then
+    LANGUAGE= LC_ALL=$LOCALE_FR_UTF8 python prog.py > prog.out || exit 1
+    ${DIFF} prog.oku prog.out || exit 1
+  fi
+  if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no french locale is installed"
+    else
+      echo "Skipping test: no french locale is supported"
+    fi
+    rm -fr $tmpfiles; exit 77
+  fi
+else
+  if test $LOCALE_FR = none; then
+    if test -f /usr/bin/localedef; then
+      echo "Skipping test: no traditional french locale is installed"
+    else
+      echo "Skipping test: no traditional french locale is supported"
+    fi
+    rm -fr $tmpfiles; exit 77
+  fi
 fi
 
 rm -fr $tmpfiles
