import 0.18

diff --git a/gettext-tools/tests/lang-tcl b/gettext-tools/tests/lang-tcl
--- a/gettext-tools/tests/lang-tcl
+++ b/gettext-tools/tests/lang-tcl
@@ -8,6 +8,9 @@
 # but not in the fr_FR.UTF-8 locale. Probably because in the fr_FR locale,
 # nl_langinfo(CODESET) returns "".
 
+# Note: This test fails on Cygwin 1.7.2 in the fr_FR.UTF-8 locale but not
+# in the fr_FR.ISO-8859-1 locale.
+
 tmpfiles=""
 trap 'rm -fr $tmpfiles' 1 2 3 15
 
@@ -25,7 +28,7 @@ tmpfiles="$tmpfiles prog.tmp prog.pot"
 : ${XGETTEXT=xgettext}
 ${XGETTEXT} -o prog.tmp --omit-header -k_ program.tcl
 test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-tr -d '\r' < prog.tmp > prog.pot
+LC_ALL=C tr -d '\r' < prog.tmp > prog.pot
 test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 tmpfiles="$tmpfiles prog.ok"
@@ -63,7 +66,7 @@ tmpfiles="$tmpfiles fr.po.tmp fr.po.new"
 : ${MSGMERGE=msgmerge}
 ${MSGMERGE} -q -o fr.po.tmp fr.po prog.pot
 test $? = 0 || { rm -fr $tmpfiles; exit 1; }
-tr -d '\r' < fr.po.tmp > fr.po.new
+LC_ALL=C tr -d '\r' < fr.po.tmp > fr.po.new
 test $? = 0 || { rm -fr $tmpfiles; exit 1; }
 
 : ${DIFF=diff}
@@ -100,11 +103,13 @@ EOF
 : ${LOCALE_FR=fr_FR}
 : ${LOCALE_FR_UTF8=fr_FR.UTF-8}
 if test $LOCALE_FR != none; then
-  LANGUAGE= LANG=$LOCALE_FR LC_MESSAGES= LC_CTYPE= LC_ALL= tclsh program.tcl > prog.out || exit 1
+  LANGUAGE= LANG=$LOCALE_FR LC_MESSAGES= LC_CTYPE= LC_ALL= tclsh program.tcl > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.ok prog.out || exit 1
 fi
 if test $LOCALE_FR_UTF8 != none; then
-  LANGUAGE= LANG=$LOCALE_FR_UTF8 LC_MESSAGES= LC_CTYPE= LC_ALL= tclsh program.tcl > prog.out || exit 1
+  LANGUAGE= LANG=$LOCALE_FR_UTF8 LC_MESSAGES= LC_CTYPE= LC_ALL= tclsh program.tcl > prog.tmp || exit 1
+  LC_ALL=C tr -d '\r' < prog.tmp > prog.out || exit 1
   ${DIFF} prog.oku prog.out || exit 1
 fi
 if test $LOCALE_FR = none && test $LOCALE_FR_UTF8 = none; then
